---
#
# Configure Server Profiles
#
# The hosts group used is provided by the group variable or defaulted to 'Intersight_Servers'.
# You can specify a specific host (or host group) on the command line:
#   ansible-playbook ... -e group=<your host group>
#   e.g., ansible-playbook server_profiles.yml -e group=TME_Demo
#
- hosts: "{{ group | default('Intersight_Servers') }}"
  connection: local
  collections:
    - cisco.intersight
  gather_facts: false
  vars:
    # Create an anchor for api_info that can be used throughout the file
    api_info: &api_info
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"
    # Server Profile name default
    profile_name: "SP-{{ inventory_hostname }}"
  tasks:
    #
    # Configure profiles specific to server (run for each server in the inventory)
    #
    - name: "Configure {{ profile_name }} Server Profile"
      intersight_server_profile:
        <<: *api_info
        organization: DevNet
        name: "{{ profile_name }}"
        tags:
          - Key: Site
            Value: SJC02
        description: "Updated Profile for server name {{ inventory_hostname }}"
        assigned_server: "{{ server_moid }}"
        # bios_policy:
        boot_order_policy: COS-Boot
        # device_connector_policy:
        # serial_over_lan_policy:
        # ipmi_over_lan_policy:
        local_user_policy: guest-admin
        ntp_policy: lab-ntp
        virtual_media_policy: COS-VM
        # sd_card_policy:
        # lan_connectivity_policy:
        # san_connectivity_policy:
      when: server_moid is defined
      delegate_to: localhost
