---
#
# Configure Server Policies and Profiles
#
# The hosts group used is provided by the group variable or defaulted to 'Intersight_Servers'.
# You can specify a specific host (or host group) on the command line:
#   ansible-playbook ... -e group=<your host group>
#   e.g., ansible-playbook server_profiles.yml -e group=TME_Demo
#
- hosts: "{{ group | default('Intersight_Servers') }}"
  connection: local
  collections:
    - cisco.intersight
  gather_facts: false
  vars:
    # Create an anchor for api_info that can be used throughout the file
    api_info: &api_info
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"
  tasks:
    #
    # Enclose workflow tasks in a block that runs once
    #
    - block:
        - name: Get vCenter Moid
          intersight_rest_api:
            <<: *api_info
            resource_path: /asset/DeviceRegistrations
            query_params:
              $filter: DeviceHostname eq '172.28.225.220'
          register: vcenter
        - name: Execute OVA deploy workflow
          intersight_rest_api:
            <<: *api_info
            resource_path: /workflow/WorkflowInfos
            update_method: post
            api_body: {
              "Name": "ucspe_vm",
              "Organization": {
                # "Moid":"5dde9f116972652d33539d39",
                "Selector": "Name eq 'default'",
                "ObjectType": "organization.Organization"
              },
              "Action": "Start",
              "Input": {
                "Vcenter": {
                  # "Moid":"5e7511176f72612d31368e2c",
                  "Moid": "{{ vcenter.api_response.Moid }}",
                  "ObjectType":"asset.DeviceRegistration"
                },
                "Datastore": "Atlanta Data",
                "Image":"http://172.28.224.62/UCSPE_4.0.4e.ova",
                "VmName":"ucspe-4-0-4e-orch",
                "PowerOn":true,
                "Datacenter":"SJC07",
                "Cluster":"Atlanta"
              },
              "WorkflowDefinition": {
                # "Moid":"5eb59e6a696f6e2d31583974",
                "Selector": "Name eq 'ucspe_vm'",
                "ObjectType":"workflow.WorkflowDefinition"
              },
              "WorkflowCtx": {
                "InitiatorCtx": {
                  # "InitiatorMoid":"5eb59e6a696f6e2d31583974",
                  "InitiatorName":"ucspe_vm",
                  "InitiatorType":"workflow.WorkflowDefinition"
                }
              }
            }
          register: workflow
        - name: Get status of OVA deploy workflow
          intersight_rest_api:
            <<: *api_info
            resource_path: /workflow/WorkflowInfos
            query_params:
              $expand: ParentTaskInfo($select=WorkflowInfo;$expand=WorkflowInfo($select=WorkflowDefinition))
              $filter: "Moid eq '{{ workflow.api_response.Moid }}'"
          register: status
          until: status.api_response.Status != 'RUNNING' and status.api_response.Status != 'WAITING'
          retries: 10
          delay: 60
          ignore_errors: true
        - debug:
            msg: "Final workflow status: {{ status.api_response.Status }}"
      run_once: true
      delegate_to: localhost
